// This file is automatically generated
//
// Command line: ./scripts/gen_kernel_abi.sh src/kernel_abi.rs
// Date: 20190518
//
// Eventually, syscall numbers will make it to the libc crate, and then we can
// remove this.

use libc::c_long;

#[allow(non_upper_case_globals)]
pub const SYS_epoll_create: c_long = 213;
#[allow(non_upper_case_globals)]
pub const SYS_io_uring_register: c_long = 427;
#[allow(non_upper_case_globals)]
pub const SYS_io_uring_enter: c_long = 426;
#[allow(non_upper_case_globals)]
pub const SYS_io_uring_setup: c_long = 425;
