// This file is automatically generated
//
// Command line: src/kernel_abi.rs
// Date: 20190518
//
// Eventually, syscall numbers will make it to the libc crate, and then we can
// remove this.
pub const SYS_epoll_create: ::c_long = 213;
pub const SYS_io_uring_register: ::c_long = 427;
pub const SYS_io_uring_enter: ::c_long = 426;
pub const SYS_io_uring_setup: ::c_long = 425;
